package com.hx.vertx.jobtask.constant;

/**
 * 执行SQL
 */
public interface ScheduleSQL {

	String TASK_QUERY_SQL = "SELECT * FROM SCHEDULE_JOB_TASK WHERE TASK_STATUS = ? AND STATUS != ?";
	String TASK_DO_UPDATE = "UPDATE SCHEDULE_JOB_TASK SET STATUS = ?,UPDATE_TIME = ?,VERSION = ? WHERE ID = ? AND VERSION = ?";
	String TASK_DONE_UPDATE = "UPDATE SCHEDULE_JOB_TASK SET STATUS = ?,COMPLETE = ?,UPDATE_TIME = ?,VERSION = ? WHERE ID = ? AND VERSION = ?";
	String TASK_LOG_INSERT = "INSERT INTO FS_SCHEDULE_TASK_LOG (ID,JOB_NAME,STATUS,MSG,VERSION,CREATE_TIME,UPDATE_TIME,EFFECTIVE) " +
			"VALUES (?,?,?,?,?,?,?,?)";
	String TASK_LOG_UPDATE = "UPDATE FS_SCHEDULE_TASK_LOG SET STATUS = ?,MSG = ?,UPDATE_TIME = ?,VERSION = ? WHERE ID = ?";
}
